name: Disney Adventure Blog
description:
meta_description: "Things to do in Disney that are not rides"

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

logo: false
paginate: 15
baseurl: /
domain_name: 'http://disneyadventureblog.github.io'
google_analytics: 'UA-60067944-1'

# Details for the RSS feed generator
url:            'http://disneyadventureblog.github.io'
author:         'Vader Cat'

gems: [jekyll-paginate]


link_sotmk: '/sotmk.html'
link_pirates: '/pirates.html'
link_we: '/we.html'
link_agents: '/agent-p.html'
link_space: '/space.html'
link_cars: '/cars.html'
